/* 
 * PI Web API 2016 R2 Swagger definition
 *
 * RESTful client for PI Web API 2016 R2
 *
 * OpenAPI spec version: v1
 * Contact: pidevclub@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace OSIsoft.PIDevClub.PIWebApiClient.Model
{
    /// <summary>
    /// PISearchCrawlerSetting
    /// </summary>
    [DataContract]
    public partial class PISearchCrawlerSetting :  IEquatable<PISearchCrawlerSetting>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PISearchCrawlerSetting" /> class.
        /// </summary>
        /// <param name="ScanInterval">Gets or sets the Scan interval for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database.</param>
        /// <param name="PointAttributes">Gets or sets the point attributes for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database.</param>
        /// <param name="CrawlerIndexBatchSize">Number of items the crawler indexes at a time.</param>
        public PISearchCrawlerSetting(int? ScanInterval = null, List<string> PointAttributes = null, int? CrawlerIndexBatchSize = null)
        {
            this.ScanInterval = ScanInterval;
            this.PointAttributes = PointAttributes;
            this.CrawlerIndexBatchSize = CrawlerIndexBatchSize;
        }
        
        /// <summary>
        /// Gets or sets the Scan interval for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database
        /// </summary>
        /// <value>Gets or sets the Scan interval for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database</value>
        [DataMember(Name="ScanInterval", EmitDefaultValue=false)]
        public int? ScanInterval { get; set; }
        /// <summary>
        /// Gets or sets the point attributes for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database
        /// </summary>
        /// <value>Gets or sets the point attributes for this {OSIsoft.REST.Models.Search.CrawlerSettings} as read from the database</value>
        [DataMember(Name="PointAttributes", EmitDefaultValue=false)]
        public List<string> PointAttributes { get; set; }
        /// <summary>
        /// Number of items the crawler indexes at a time
        /// </summary>
        /// <value>Number of items the crawler indexes at a time</value>
        [DataMember(Name="CrawlerIndexBatchSize", EmitDefaultValue=false)]
        public int? CrawlerIndexBatchSize { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PISearchCrawlerSetting {\n");
            sb.Append("  ScanInterval: ").Append(ScanInterval).Append("\n");
            sb.Append("  PointAttributes: ").Append(PointAttributes).Append("\n");
            sb.Append("  CrawlerIndexBatchSize: ").Append(CrawlerIndexBatchSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PISearchCrawlerSetting);
        }

        /// <summary>
        /// Returns true if PISearchCrawlerSetting instances are equal
        /// </summary>
        /// <param name="other">Instance of PISearchCrawlerSetting to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PISearchCrawlerSetting other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ScanInterval == other.ScanInterval ||
                    this.ScanInterval != null &&
                    this.ScanInterval.Equals(other.ScanInterval)
                ) && 
                (
                    this.PointAttributes == other.PointAttributes ||
                    this.PointAttributes != null &&
                    this.PointAttributes.SequenceEqual(other.PointAttributes)
                ) && 
                (
                    this.CrawlerIndexBatchSize == other.CrawlerIndexBatchSize ||
                    this.CrawlerIndexBatchSize != null &&
                    this.CrawlerIndexBatchSize.Equals(other.CrawlerIndexBatchSize)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ScanInterval != null)
                    hash = hash * 59 + this.ScanInterval.GetHashCode();
                if (this.PointAttributes != null)
                    hash = hash * 59 + this.PointAttributes.GetHashCode();
                if (this.CrawlerIndexBatchSize != null)
                    hash = hash * 59 + this.CrawlerIndexBatchSize.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
